language: node_js
node_js:
  - "10"
before_script:
- chmod +x ./prebuild.sh
- chmod +x ./deploy.sh
- ./prebuild.sh
- yarn install

script:
  - yarn build
  - yarn test --colors
  - sh deploy.sh

env:
  global:
  - GH_REPO="marabesi/github-stats-dashboard"